/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOATANBACK
#define ROOATANBACK

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooATanBack : public RooAbsPdf {
public:
  RooATanBack() {} ; 
  RooATanBack(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _a,
	      RooAbsReal& _b,
	      RooAbsReal& _c,
	      RooAbsReal& _mr);
  RooATanBack(const RooATanBack& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooATanBack(*this,newname); }
  inline virtual ~RooATanBack() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;


protected:

  RooRealProxy x ;
  RooRealProxy a ;
  RooRealProxy b ;
  RooRealProxy c ;
  RooRealProxy mr ;
  
  Double_t evaluate() const ;



private:

  double theNorm(const double value) const;

  ClassDef(RooATanBack,1) // Your description goes here...
};
 
#endif
