mumu_PT:
  fit_vars: [bplus_DIRA_OWNPV, bplus_IPCHI2_OWNPV, bplus_LOKI_DTF_CHI2NDOF, bplus_FDCHI2_OWNPV, bplus_ETA, pion1_IPCHI2_OWNPV, pion2_IPCHI2_OWNPV, kaon_IPCHI2_OWNPV, muplus_IPCHI2_OWNPV, muminus_IPCHI2_OWNPV, muplus_PT, muminus_PT]
  max_depth: 6
  n_estimators: 600  
  learning_rate: 0.1